server:
  port: 13002
spring:
  config:
    import:
      - optional:classpath:.env[.properties]
      - classpath:config/agent.yml
      - classpath:config/vector.yml
      - classpath:config/mysql.yml
      - classpath:config/minio.yml
      - classpath:config/tool-env.yml